import QtQuick
import Quickshell
import Quickshell.Io
import qs.modules.common

QtObject {
    id: root

    property bool hyprGlassLoaded: false
    property bool hyprGlassInstalled: false
    property bool hyprGlassWasEnabled: false
    property bool shellManagedPlugin: false
    property bool configApplied: false
    property bool ready: false
    property string status: "probing"
    property string errorMessage: ""

    property bool checkingAfterLoad: false
    readonly property bool darkMode: Appearance.m3colors.darkmode

    function stripAnsi(text) {
        return text.replace(/\x1B\[[0-?]*[ -\/]*[@-~]/g, "");
    }

    function finish(statusValue, errorValue) {
        root.status = statusValue;
        root.errorMessage = errorValue ?? "";
        root.ready = true;
    }

    function probeLoaded(afterLoad) {
        if (loadedProbe.running)
            return;

        root.ready = false;
        root.status = "probing";
        root.checkingAfterLoad = afterLoad ?? false;
        loadedProbe.running = true;
    }

    function probeHyprpm() {
        if (hyprpmProbe.running)
            return;

        root.status = "probing";
        hyprpmProbe.running = true;
    }

    function loadManagedPlugin() {
        if (hyprpmEnable.running || hyprpmReload.running)
            return;

        // Claim ownership before starting hyprpm so teardown can always roll
        // back a partially completed enable sequence.
        root.shellManagedPlugin = true;
        root.status = "loading";
        hyprpmEnable.running = true;
    }

    function reloadUserEnabledPlugin() {
        if (hyprpmReload.running)
            return;

        root.status = "loading";
        hyprpmReload.running = true;
    }

    function buildGlassConfigCommand() {
        const theme = root.darkMode ? "dark" : "light";
        return `
set -eu
fragment="$HOME/.config/hypr/hyprland/shellOverrides/liquid-glass.lua"
mkdir -p "$(dirname "$fragment")"
cat > "$fragment" <<'VYNX_LIQUID_GLASS'
-- Generated by ii-vynx while Liquid Glass is active. Do not edit.
if hl.plugin.hyprglass then
    local hg = hl.plugin.hyprglass

    hg.config({
        enabled = false,
        manage_window_blur = false,
        default_theme = "${theme}",
        default_preset = "vynx",
        layers = { enabled = true },
    })

    hg.preset("vynx", {
        inherits = "subtle",
        blur_strength = 1.0,
        blur_iterations = 2,
        refraction_strength = 0.45,
        chromatic_aberration = 0.10,
        fresnel_strength = 0.35,
        specular_strength = 0.45,
        glass_opacity = 1.0,
        edge_thickness = 0.05,
        lens_distortion = 0.18,
        tint_color = 0xffffff0a,
        dark = {
            brightness = 0.86,
            contrast = 0.94,
            saturation = 0.88,
            vibrancy = 0.12,
            adaptive_dim = 0.25,
        },
        light = {
            brightness = 1.06,
            contrast = 0.94,
            saturation = 0.90,
            vibrancy = 0.10,
            adaptive_boost = 0.25,
        },
    })

    hg.layer("quickshell:bar", { preset = "vynx", mask_threshold = 0.05 })
    hg.layer("quickshell:verticalBar", { preset = "vynx", mask_threshold = 0.05 })
    hg.layer("quickshell:popup", { preset = "vynx", mask_threshold = 0.05 })
end
VYNX_LIQUID_GLASS
hyprctl reload
`;
    }

    function applyConfig() {
        if (configApply.running)
            return;

        root.ready = false;
        root.status = "configuring";
        configApply.command = ["sh", "-c", root.buildGlassConfigCommand()];
        configApply.running = true;
    }

    function shutdown() {
        const managed = root.shellManagedPlugin;
        root.shellManagedPlugin = false;
        root.configApplied = false;

        Quickshell.execDetached([
            "sh",
            "-c",
            managed
                ? "rm -f \"$HOME/.config/hypr/hyprland/shellOverrides/liquid-glass.lua\"; hyprpm disable hyprglass >/dev/null 2>&1; hyprpm reload >/dev/null 2>&1"
                : "rm -f \"$HOME/.config/hypr/hyprland/shellOverrides/liquid-glass.lua\"; hyprctl reload >/dev/null 2>&1"
        ]);
    }

    Component.onCompleted: root.probeLoaded(false)
    Component.onDestruction: root.shutdown()

    onDarkModeChanged: {
        if (root.configApplied && root.hyprGlassLoaded)
            root.applyConfig();
    }

    Process {
        id: loadedProbe
        running: false
        command: ["hyprctl", "-j", "plugin", "list"]

        stdout: StdioCollector {
            id: loadedOutput
        }
        stderr: StdioCollector {
            id: loadedError
        }

        onExited: (exitCode, exitStatus) => {
            let loaded = false;

            if (exitCode === 0) {
                try {
                    const plugins = JSON.parse(loadedOutput.text);
                    loaded = plugins.some(plugin => String(plugin.name).toLowerCase() === "hyprglass");
                } catch (error) {
                    root.finish("error", "Could not parse Hyprland plugin state.");
                    return;
                }
            } else {
                root.finish("error", loadedError.text.trim() || "Could not query Hyprland plugins.");
                return;
            }

            root.hyprGlassLoaded = loaded;

            if (loaded) {
                root.applyConfig();
                return;
            }

            if (root.checkingAfterLoad) {
                root.finish("error", "HyprGlass did not load after hyprpm reload.");
                return;
            }

            root.probeHyprpm();
        }
    }

    Process {
        id: hyprpmProbe
        running: false
        command: ["sh", "-c", "command -v hyprpm >/dev/null 2>&1 && hyprpm list"]

        stdout: StdioCollector {
            id: hyprpmOutput
        }
        stderr: StdioCollector {
            id: hyprpmError
        }

        onExited: (exitCode, exitStatus) => {
            if (exitCode !== 0) {
                root.finish("unavailable", hyprpmError.text.trim() || "hyprpm is not available.");
                return;
            }

            const clean = root.stripAnsi(hyprpmOutput.text);
            const lower = clean.toLowerCase();
            const marker = lower.indexOf("plugin hyprglass");

            if (marker === -1) {
                root.finish("unavailable", "HyprGlass is not installed through hyprpm.");
                return;
            }

            root.hyprGlassInstalled = true;

            const pluginBlock = clean.slice(marker, marker + 320);
            const enabledMatch = pluginBlock.match(/enabled:\s*(true|false)/i);
            if (!enabledMatch) {
                root.finish("error", "Could not determine HyprGlass hyprpm state.");
                return;
            }

            root.hyprGlassWasEnabled = enabledMatch[1].toLowerCase() === "true";

            if (root.hyprGlassWasEnabled)
                root.reloadUserEnabledPlugin();
            else
                root.loadManagedPlugin();
        }
    }

    Process {
        id: hyprpmEnable
        running: false
        command: ["hyprpm", "enable", "hyprglass"]

        stderr: StdioCollector {
            id: hyprpmEnableError
        }

        onExited: (exitCode, exitStatus) => {
            if (exitCode !== 0) {
                root.shellManagedPlugin = false;
                root.finish("error", hyprpmEnableError.text.trim() || "Could not enable HyprGlass.");
                return;
            }

            root.reloadUserEnabledPlugin();
        }
    }

    Process {
        id: hyprpmReload
        running: false
        command: ["hyprpm", "reload"]

        stderr: StdioCollector {
            id: hyprpmReloadError
        }

        onExited: (exitCode, exitStatus) => {
            if (exitCode !== 0) {
                root.finish("error", hyprpmReloadError.text.trim() || "Could not reload Hyprland plugins.");
                return;
            }

            root.probeLoaded(true);
        }
    }

    Process {
        id: configApply
        running: false
        command: ["true"]

        stderr: StdioCollector {
            id: configApplyError
        }

        onExited: (exitCode, exitStatus) => {
            if (exitCode !== 0) {
                root.finish("error", configApplyError.text.trim() || "Could not configure HyprGlass.");
                return;
            }

            root.configApplied = true;
            root.finish(root.shellManagedPlugin ? "managed" : "user", "");
        }
    }
}
