import QtQuick
import Quickshell
import Quickshell.Io
import qs.modules.common

QtObject {
    id: root

    property bool hyprGlassLoaded: false
    property bool hyprGlassInstalled: false
    property bool shellManagedPlugin: false
    property bool configApplied: false
    property bool ready: false
    property string status: "probing"
    property string errorMessage: ""

    property string hyprlandVersion: ""
    property string hyprlandCommit: ""
    property string hyprlandAbiSuffix: ""
    property string managedPluginPath: ""
    property bool checkingAfterLoad: false
    readonly property bool darkMode: Appearance.m3colors.darkmode

    function finish(statusValue, errorValue) {
        root.status = statusValue;
        root.errorMessage = errorValue ?? "";
        root.ready = true;
    }

    function probeLoaded(afterLoad) {
        if (loadedProbe.running)
            return;

        root.ready = false;
        root.status = "probing";
        root.checkingAfterLoad = afterLoad ?? false;
        loadedProbe.running = true;
    }

    function probeHyprlandVersion() {
        if (versionProbe.running)
            return;

        root.status = "probing";
        versionProbe.running = true;
    }

    function probeBundledPlugin() {
        if (bundleProbe.running)
            return;

        if (!/^_aq_[0-9]+(\.[0-9]+)+(_[a-z]+_[0-9]+(\.[0-9]+)+)+$/.test(root.hyprlandAbiSuffix)) {
            root.finish("error", "Hyprland returned an invalid dependency ABI identifier.");
            return;
        }

        root.status = "probing";
        bundleProbe.command = [
            "sh",
            "-c",
            `plugin="$HOME/.local/lib/ii-vynx/hyprglass/${root.hyprlandAbiSuffix}/hyprglass.so"
            test -f "$plugin" || exit 66
            command -v ldd >/dev/null 2>&1 || exit 68
            deps="$(ldd "$plugin" 2>&1)" || { printf '%s\\n' "$deps" >&2; exit 67; }
            if printf '%s\\n' "$deps" | grep -q 'not found'; then
                printf '%s\\n' "$deps" | grep 'not found' >&2
                exit 67
            fi
            printf '%s\\n' "$plugin"`
        ];
        bundleProbe.running = true;
    }

    function loadManagedPlugin() {
        if (pluginLoad.running || root.managedPluginPath.length === 0)
            return;

        // Claim ownership before loading so teardown can roll back if the
        // runtime is destroyed between hyprctl load and the completion probe.
        root.shellManagedPlugin = true;
        root.status = "loading";
        pluginLoad.command = ["hyprctl", "plugin", "load", root.managedPluginPath];
        pluginLoad.running = true;
    }

    function buildGlassConfigCommand() {
        const theme = root.darkMode ? "dark" : "light";
        return `
set -eu
fragment="$HOME/.config/hypr/hyprland/shellOverrides/liquid-glass.lua"
mkdir -p "$(dirname "$fragment")"
cat > "$fragment" <<'VYNX_LIQUID_GLASS'
-- Generated by ii-vynx while Liquid Glass is active. Do not edit.
if hl.plugin.hyprglass then
    local hg = hl.plugin.hyprglass

    hg.config({
        enabled = false,
        manage_window_blur = false,
        default_theme = "${theme}",
        default_preset = "vynx",
        layers = { enabled = true },
    })

    hg.preset("vynx", {
        inherits = "subtle",
        blur_strength = 1.0,
        blur_iterations = 2,
        refraction_strength = 0.45,
        chromatic_aberration = 0.10,
        fresnel_strength = 0.35,
        specular_strength = 0.45,
        glass_opacity = 1.0,
        edge_thickness = 0.05,
        lens_distortion = 0.18,
        tint_color = 0xffffff0a,
        dark = {
            brightness = 0.86,
            contrast = 0.94,
            saturation = 0.88,
            vibrancy = 0.12,
            adaptive_dim = 0.25,
        },
        light = {
            brightness = 1.06,
            contrast = 0.94,
            saturation = 0.90,
            vibrancy = 0.10,
            adaptive_boost = 0.25,
        },
    })

    hg.layer("quickshell:bar", { preset = "vynx", mask_threshold = 0.05 })
    hg.layer("quickshell:verticalBar", { preset = "vynx", mask_threshold = 0.05 })
    hg.layer("quickshell:popup", { preset = "vynx", mask_threshold = 0.05 })
end
VYNX_LIQUID_GLASS
hyprctl reload
`;
    }

    function applyConfig() {
        if (configApply.running)
            return;

        root.ready = false;
        root.status = "configuring";
        configApply.command = ["sh", "-c", root.buildGlassConfigCommand()];
        configApply.running = true;
    }

    function shutdown() {
        const managed = root.shellManagedPlugin;
        const pluginPath = root.managedPluginPath;
        root.shellManagedPlugin = false;
        root.configApplied = false;

        if (managed && pluginPath.length > 0) {
            Quickshell.execDetached([
                "sh",
                "-c",
                "rm -f \"$HOME/.config/hypr/hyprland/shellOverrides/liquid-glass.lua\"; hyprctl plugin unload \"$1\" >/dev/null 2>&1 || true; hyprctl reload >/dev/null 2>&1",
                "vynx-liquid-glass",
                pluginPath
            ]);
            return;
        }

        Quickshell.execDetached([
            "sh",
            "-c",
            "rm -f \"$HOME/.config/hypr/hyprland/shellOverrides/liquid-glass.lua\"; hyprctl reload >/dev/null 2>&1"
        ]);
    }

    Component.onCompleted: root.probeLoaded(false)
    Component.onDestruction: root.shutdown()

    onDarkModeChanged: {
        if (root.configApplied && root.hyprGlassLoaded)
            root.applyConfig();
    }

    Process {
        id: loadedProbe
        running: false
        command: ["hyprctl", "-j", "plugin", "list"]

        stdout: StdioCollector {
            id: loadedOutput
        }
        stderr: StdioCollector {
            id: loadedError
        }

        onExited: (exitCode, exitStatus) => {
            let loaded = false;

            if (exitCode === 0) {
                try {
                    const plugins = JSON.parse(loadedOutput.text);
                    loaded = plugins.some(plugin => String(plugin.name).toLowerCase() === "hyprglass");
                } catch (error) {
                    root.finish("error", "Could not parse Hyprland plugin state.");
                    return;
                }
            } else {
                root.finish("error", loadedError.text.trim() || "Could not query Hyprland plugins.");
                return;
            }

            root.hyprGlassLoaded = loaded;

            if (loaded) {
                root.hyprGlassInstalled = true;
                root.applyConfig();
                return;
            }

            if (root.checkingAfterLoad) {
                root.finish("error", "HyprGlass did not load after hyprctl plugin load.");
                return;
            }

            root.probeHyprlandVersion();
        }
    }

    Process {
        id: versionProbe
        running: false
        command: ["hyprctl", "-j", "version"]

        stdout: StdioCollector {
            id: versionOutput
        }
        stderr: StdioCollector {
            id: versionError
        }

        onExited: (exitCode, exitStatus) => {
            if (exitCode !== 0) {
                root.finish("error", versionError.text.trim() || "Could not query the Hyprland version.");
                return;
            }

            try {
                const version = JSON.parse(versionOutput.text);
                root.hyprlandVersion = String(version.version ?? "").trim();
                root.hyprlandCommit = String(version.commit ?? "").trim();
                const abiHash = String(version.abiHash ?? "").trim();
                const abiMarker = abiHash.indexOf("_aq_");
                root.hyprlandAbiSuffix = abiMarker >= 0 ? abiHash.slice(abiMarker) : "";
            } catch (error) {
                root.finish("error", "Could not parse the Hyprland version.");
                return;
            }

            root.probeBundledPlugin();
        }
    }

    Process {
        id: bundleProbe
        running: false
        command: ["true"]

        stdout: StdioCollector {
            id: bundleOutput
        }
        stderr: StdioCollector {
            id: bundleError
        }

        onExited: (exitCode, exitStatus) => {
            if (exitCode === 66) {
                root.finish("unavailable", `No bundled HyprGlass build for Hyprland ${root.hyprlandVersion} ABI ${root.hyprlandAbiSuffix}.`);
                return;
            }

            if (exitCode === 67) {
                root.finish("unavailable", bundleError.text.trim() || "Bundled HyprGlass has unresolved runtime dependencies.");
                return;
            }

            if (exitCode === 68) {
                root.finish("unavailable", "Could not validate bundled HyprGlass runtime dependencies because ldd is unavailable.");
                return;
            }

            if (exitCode !== 0) {
                root.finish("error", bundleError.text.trim() || "Could not resolve the bundled HyprGlass plugin.");
                return;
            }

            root.managedPluginPath = bundleOutput.text.trim();
            if (root.managedPluginPath.length === 0) {
                root.finish("error", "Bundled HyprGlass path was empty.");
                return;
            }

            root.hyprGlassInstalled = true;
            root.loadManagedPlugin();
        }
    }

    Process {
        id: pluginLoad
        running: false
        command: ["true"]

        stderr: StdioCollector {
            id: pluginLoadError
        }

        onExited: (exitCode, exitStatus) => {
            if (exitCode !== 0) {
                root.shellManagedPlugin = false;
                root.finish("error", pluginLoadError.text.trim() || "Could not load the bundled HyprGlass plugin.");
                return;
            }

            root.probeLoaded(true);
        }
    }

    Process {
        id: configApply
        running: false
        command: ["true"]

        stderr: StdioCollector {
            id: configApplyError
        }

        onExited: (exitCode, exitStatus) => {
            if (exitCode !== 0) {
                root.finish("error", configApplyError.text.trim() || "Could not configure HyprGlass.");
                return;
            }

            root.configApplied = true;
            root.finish(root.shellManagedPlugin ? "managed" : "user", "");
        }
    }
}
